g_jp_template_index = {
	tplTextureTitle    : "Texture Report" ,
	tplTextureExplain  : "Texture のImport Settingsを確認できます" ,
	tplAudioTitle      : "Audio Report" ,
	tplAudioExplain    : "AudioClipの Import Settingsを確認できます" ,
	tplModelTitle      : "Model Report" ,
	tplModelExplain    : "Modelの Import Settingsを確認できます" ,
	tplAbTitle         : "AssetBundle Report" ,
	tplAbExplain       : "AssetBundleの Import Settingsを確認できます" ,
	tplAbDupTitle      : "AssetBundle Duplicate Report" ,
	tplAbDupExplain    : "AssetBundle中にある重複アセットの確認が出来ます(AssetBundle Report でも、確認できます。こちらは簡易のまとめページです)" ,
	tplResourceTitle   : "Resources Report" ,
	tplResourceExplain : "Resourcesフォルダがプロジェクトにないか確認できます。" ,
	tplTipsTitle       : "Tips" , 
	tplTipsExplain     : "Tips 情報です" ,
};