g_en_template_texture = {
	// common
	tplNoPlatform			: "none",
	tplWarning				: "Warning",
	tplSearchFilter			: "SearchFilter",
	tplSearchTitle			: "Search",
	tplSearchBtn			: "Search",
	tplSearchResultTitle	: "Search Result",
	tplCheckNon				: "No Check",
	tplCheckEnableOnly		: "Enable Only",
	tplCheckDisableOnly		: "Disable Only",
	tplHitNum				: "HitNum",
	tplItem					: "Item",
	tplCheck				: "Check",
	tplCondition			: "Condition",
	tplAddConditionBtn		: "Add condition",
	tplDelConditionBtn		: "delete",
	tplFileInclude			: "If filepath includes below words",
	tplFileExclude			: "If filepath doesn't include below words",

	// specific
	tplCondBasic			: "Basic",
	tplCondFormat			: "Format",
	tplCondImportType		: "ImportType",
	tplCondTextureSize		: "TextureSize",
	tplCondMipMapCheck		: "MipMap check	",
	tplCondReadWriteCheck	: "Read/Write check	",
	tplCondPow2Check		: "Pow2 check",
    tplCheckNonPow2Only		: "Non pow2 only",
    tplCondWidth			: "Width",
	tplCondHeight			: "Height",
	tplCondSpriteTag		: "SpritePackTag",

	// in result
	tplResultPath			: "Path",
	tplResultType			: "Type",
	tplResultFormat			: "Format",
	tplResultSize			: "Size",
	tplResultNonPow2		: "isn't pow2 size",
	tplResultSpriteTag		: "SpritePackingTag",
	tplResultMaxSize		: "MaxSize",
	tplResultMipMap			: "MipMap",
	tplResultReadWrite		: "Read/Write",
};